<h2>Java运行环境</h2>
<table class="detail">
	<tr>
		<th>Java运行时名称</th>
		<td>${Request.envJava.javaRuntimeName!"无..."}</td>
	</tr>
	<tr>
		<th>Java运行时版本</th>
		<td>${Request.envJava.javaRuntimeVersion!"无..."}</td>
	</tr>
	<tr>
		<th >Java提供商</th>
		<td>${Request.envJava.javaVendor!"无..."}</td>
	</tr>
	<tr>
		<th>Java版本</th>
		<td>${Request.envJava.javaVersion!"无..."}</td>
	</tr>
	<tr>
		<th>Java虚拟机名称</th>
		<td>${Request.envJava.javaVMName!"无..."}</td>
	</tr>
	<tr>
		<th>Java虚拟机版本</th>
		<td>${Request.envJava.javaVMVersion!"无..."}</td>
	</tr>
	<tr>
		<th>Java虚拟机提供商</th>
		<td>${Request.envJava.javaVMVendor!"无..."}</td>
	</tr>
	<tr>
		<th>Java虚拟机信息</th>
		<td>${Request.envJava.javaVMInfo!"无..."}</td>
	</tr>
	<tr>
		<th>Java主目录</th>
		<td>${Request.envJava.javaHome!"无..."}</td>
	</tr>
	<tr>
		<th>Java启动选项</th>
		<td>${Request.envJava.javaOptions!"无..."}</td>
	</tr>
	<tr>
		<th>Java类路径</th>
		<td>${Request.envJava.javaClassPath!"无..."}</td>
	</tr>
	<tr>
		<th>Java库路径</th>
		<td>${Request.envJava.javaLibraryPath!"无..."}</td>
	</tr>
</table>